### ISSUE TITLE
When listen along host skips song the progress on the last song is carried over

### ISSUE THREAD

**Issue by Tae47** [ordinall/BetterDiscord-Stuff#21] opened 2022-08-24 21:03 UTC
If the song currently playing is at 1 minute of progress and it is skipped by the host, the next song playing will start at the 1-minute mark instead of starting at the beginning.

**Comment by Florian-Mahlberg** [comment] 2022-10-12 19:06
Can't reproduce anymore - seems to be fixed with the new update?

**Comment by Florian-Mahlberg** [comment] 2022-10-13 16:10
@d0gkiller87  can you reproduce it?

**Comment by ordinall** [comment] 2022-10-13 21:02
Can't reproduce. Song syncing is the responsibility of discord and the plugin doesn't even touch that. It only spoofs premium status which should not effect any other thing. Try
- Reconnecting spotify account
- Updating spotify

**Closed as completed by ordinall** 2022-10-13 21:02 UTC
