### ISSUE TITLE
It's turning off on its own

### ISSUE THREAD

**Issue by Projeet1002** [ordinall/BetterDiscord-Stuff#19] opened 2022-08-02 17:04 UTC
the Plugin is getting turned off on its own and doesn't work even after re installing the plugin please fix this problem asap 🙏

**Comment by ordinall** [comment] 2022-08-02 17:21
duplicate of #18 , the issue has been fixed in the latest commit, restart discord to get the update

**Closed as completed by ordinall** 2022-08-02 17:21 UTC

**Comment by Projeet1002** [comment] 2022-08-03 16:00
> 

Thankss
